[package]
name = "torch-sys"
version = "0.1.0"
authors = ["SunDoge <384813529@qq.com>"]
edition = "2018"

[dependencies]

[build-dependencies]
bindgen = { git = "https://github.com/rust-lang/rust-bindgen.git" }